"""Shared status vocabulary for machine-readable kernel records."""

from enum import StrEnum


class ProvenanceClassification(StrEnum):
    AUTHENTIC_FROZEN = "AUTHENTIC_FROZEN"
    DERIVED_FROM_FROZEN = "DERIVED_FROM_FROZEN"
    HISTORICAL_POST_DATA = "HISTORICAL_POST_DATA"
    UNVERIFIED = "UNVERIFIED"
    MISSING = "MISSING"


class EquationReadiness(StrEnum):
    SYMBOLIC_READY = "SYMBOLIC_READY"
    NUMERIC_READY = "NUMERIC_READY"
    BLOCKED_MISSING_PARAMETER = "BLOCKED_MISSING_PARAMETER"
    BLOCKED_MISSING_FUNCTION = "BLOCKED_MISSING_FUNCTION"
    BLOCKED_MISSING_NUMERICAL_CONTRACT = "BLOCKED_MISSING_NUMERICAL_CONTRACT"
    BLOCKED_MISSING_FRAME = "BLOCKED_MISSING_FRAME"
    BLOCKED_MISSING_UNIT = "BLOCKED_MISSING_UNIT"
    BLOCKED_MISSING_ORIENTATION = "BLOCKED_MISSING_ORIENTATION"
    BLOCKED_MISSING_COVARIANCE = "BLOCKED_MISSING_COVARIANCE"


class ValidationSpecificationStatus(StrEnum):
    SPECIFICATION_INCOMPLETE = "SPECIFICATION_INCOMPLETE"


class ValidationReadiness(StrEnum):
    """Primary readiness states permitted by the Step 03 methodology contract."""

    READY = "READY"
    READY_EXTERNAL = "READY_EXTERNAL"
    PARTIAL = "PARTIAL"
    SENSITIVITY_ONLY = "SENSITIVITY_ONLY"
    SPECIFICATION_ONLY = "SPECIFICATION_ONLY"
    BLOCKED = "BLOCKED"
    FUTURE_ONLY = "FUTURE_ONLY"


class DataExposureClassification(StrEnum):
    MODEL_PREEXISTING = "MODEL_PREEXISTING"
    MODEL_EXPOSED = "MODEL_EXPOSED"
    POST_DATA_MODEL_CHANGE = "POST_DATA_MODEL_CHANGE"
    UNKNOWN_EXPOSURE = "UNKNOWN_EXPOSURE"


class BlindnessLevel(StrEnum):
    BLIND_STRICT = "BLIND_STRICT"
    BLIND_PARTIAL = "BLIND_PARTIAL"
    NON_BLIND_HISTORICAL = "NON_BLIND_HISTORICAL"
    FUTURE_BLIND = "FUTURE_BLIND"
